services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 6ty7ers_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
