/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvRouteImport } from './routes/tv'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientVerifyRouteImport } from './routes/patient.verify'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffCheckinRouteImport } from './routes/staff.checkin'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'
import { Route as StaffTriageRouteImport } from './routes/staff.triage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/patient/history',
  path: '/patient/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientVerifyRoute = PatientVerifyRouteImport.update({
  id: '/patient/verify',
  path: '/patient/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCheckinRoute = StaffCheckinRouteImport.update({
  id: '/staff/checkin',
  path: '/staff/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/staff/profile',
  path: '/staff/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/staff/reports',
  path: '/staff/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTriageRoute = StaffTriageRouteImport.update({
  id: '/staff/triage',
  path: '/staff/triage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tv': typeof TvRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/verify': typeof PatientVerifyRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/triage': typeof StaffTriageRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tv': typeof TvRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/verify': typeof PatientVerifyRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/triage': typeof StaffTriageRoute
  '/patient': typeof PatientIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tv': typeof TvRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/verify': typeof PatientVerifyRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/triage': typeof StaffTriageRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tv'
    | '/patient/history'
    | '/patient/verify'
    | '/staff/checkin'
    | '/staff/login'
    | '/staff/profile'
    | '/staff/reports'
    | '/staff/triage'
    | '/patient/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tv'
    | '/patient/history'
    | '/patient/verify'
    | '/staff/checkin'
    | '/staff/login'
    | '/staff/profile'
    | '/staff/reports'
    | '/staff/triage'
    | '/patient'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/tv'
    | '/patient/history'
    | '/patient/verify'
    | '/staff/checkin'
    | '/staff/login'
    | '/staff/profile'
    | '/staff/reports'
    | '/staff/triage'
    | '/patient/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TvRoute: typeof TvRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientVerifyRoute: typeof PatientVerifyRoute
  StaffCheckinRoute: typeof StaffCheckinRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffTriageRoute: typeof StaffTriageRoute
  PatientIndexRoute: typeof PatientIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/patient/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/verify': {
      id: '/patient/verify'
      path: '/patient/verify'
      fullPath: '/patient/verify'
      preLoaderRoute: typeof PatientVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/checkin': {
      id: '/staff/checkin'
      path: '/staff/checkin'
      fullPath: '/staff/checkin'
      preLoaderRoute: typeof StaffCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/staff/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/staff/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/triage': {
      id: '/staff/triage'
      path: '/staff/triage'
      fullPath: '/staff/triage'
      preLoaderRoute: typeof StaffTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TvRoute: TvRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientVerifyRoute: PatientVerifyRoute,
  StaffCheckinRoute: StaffCheckinRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffTriageRoute: StaffTriageRoute,
  PatientIndexRoute: PatientIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
