"""add department_id to staff

Revision ID: 43e1475ed584
Revises: af6d2f8ab853
Create Date: 2026-07-26 19:06:07.263745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e1475ed584'
down_revision: Union[str, Sequence[str], None] = 'af6d2f8ab853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'staff', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'department_id')
    # ### end Alembic commands ###
