"""Initial schema

Revision ID: 79dfbd94357c
Revises: 
Create Date: 2026-07-09 16:07:30.491154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79dfbd94357c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_username'), 'staff', ['username'], unique=True)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_event_type'), 'system_logs', ['event_type'], unique=False)
    op.create_table('queue_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('public_token', sa.String(), nullable=False),
    sa.Column('track_type', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('t1_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('t2_called', sa.DateTime(timezone=True), nullable=True),
    sa.Column('t3_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triaged_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('consulted_by_staff_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['consulted_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['triaged_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_sessions_public_token'), 'queue_sessions', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_sessions_public_token'), table_name='queue_sessions')
    op.drop_table('queue_sessions')
    op.drop_index(op.f('ix_system_logs_event_type'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_staff_username'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('patients')
    # ### end Alembic commands ###
