"""Add reason and staff dept

Revision ID: acfc6ffd7e7d
Revises: 43e1475ed584
Create Date: 2026-07-26 21:20:43.473514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfc6ffd7e7d'
down_revision: Union[str, Sequence[str], None] = '43e1475ed584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_sessions', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_sessions', 'reason')
    # ### end Alembic commands ###
