"""Add OTP fields to Patient

Revision ID: f01ba7243a99
Revises: 4090003ef58c
Create Date: 2026-07-16 13:36:13.276142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01ba7243a99'
down_revision: Union[str, Sequence[str], None] = '4090003ef58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'otp_expires_at')
    op.drop_column('patients', 'otp_code')
    # ### end Alembic commands ###
